name: Build and Publish

on:
  push:
    branches: [ "main" ]
  workflow_call:
  schedule:
    - cron: '0 0 1 * *'

env:
  REGISTRY: ghcr.io

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build Go Binary
        run: env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o gompeg ./main.go

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gompeg-binary
          path: gompeg
          retention-days: 14

  build-docker:
    needs: build-binary
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        variant: [scratch, nvidia]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Binary Artifact
        uses: actions/download-artifact@v4
        with:
          name: gompeg-binary

      # Downcase the repository name to satisfy Docker registry specifications
      - name: Lowercase Repository Name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VARIANT=${{ matrix.variant }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:ffmpeg-${{ matrix.variant }}
